from fabric.utils.helpers import get_relative_path

DEFAULTS = {
    "wallpapers_dir": get_relative_path("../assets/wallpapers_example"),
    "bar_position": "Top",
    "vertical": False,
    "centered_bar": False,
    "datetime_12h_format": False,
    "terminal_command": "kitty -e",
    "dock_enabled": True,
    "dock_icon_size": 28,
    "dock_always_show": False,
    "bar_workspace_show_number": False,
    "bar_workspace_use_chinese_numerals": False,
    "bar_hide_special_workspace": True,
    "bar_theme": "Pills",
    "dock_theme": "Pills",
    "panel_theme": "Notch",
    "panel_position": "Center",
    "notif_pos": "Top",
    "bar_button_apps_visible": True,
    "bar_systray_visible": True,
    "bar_control_visible": True,
    "bar_network_visible": True,
    "bar_button_tools_visible": True,
    "bar_sysprofiles_visible": True,
    "bar_button_overview_visible": True,
    "bar_ws_container_visible": True,
    "bar_weather_visible": True,
    "bar_battery_visible": True,
    "bar_metrics_visible": True,
    "bar_language_visible": True,
    "bar_date_time_visible": True,
    "bar_button_power_visible": True,
    "corners_visible": True,
    "bar_metrics_disks": ["/"],
    "metrics_visible": {
        "cpu": True,
        "ram": True,
        "disk": True,
        "gpu": True,
    },
    "metrics_small_visible": {
        "cpu": True,
        "ram": True,
        "disk": True,
        "gpu": True,
    },
    "limited_apps_history": ["Spotify"],
    "history_ignored_apps": ["Hyprshot"],
    "selected_monitors": [],
    "weather_location": "",
    "dashboard_kanban_visible": True,
    "dashboard_pins_visible": True,
    "dashboard_wallpapers_visible": True,
    "dashboard_mixer_visible": True,
}
